---
title: "Meta 3 - ANOVA 3 "
output: 
  html_notebook: 
    toc: yes
    toc_float:
      collapsed: false
    number_sections: true
---

# Dependencies ---------------

```{r Libraries}
#ibrary(readr)
install.packages("ggplot2")
library(ggplot2)
install.packages("dplyr")
library(dplyr)
install.packages("car")
library(car)
#install.packages("scatterplot3d", dependencies = TRUE)
library(scatterplot3d)
#install.packages("rgl")
#library(rgl)
#options(rgl.printRglwidget = TRUE)
install.packages("ggpubr")
library("ggpubr")
require("dplyr")
```

# Dinic

```{r Load data set}
df <- read.csv(file = "results_tests_ek.csv", header=TRUE)
df$alg = factor(df$alg)
df$n = factor(df$n)
df$p = factor(df$p)
```

## Analysis ---------------

```{r Summary of data}
summary(df)
```
## Visualizing

```{r Interactions}
ggline(df, x = "p", y = "time", color = "n", add = c("mean_se"))
ggline(df, x = "n", y = "time", color = "p", add = c("mean_se"))
interaction.plot(x.factor = df$p, trace.factor = df$n, 
                 response = df$time, fun = mean, 
                 type = "b", legend = TRUE, 
                 xlab = "prob", ylab="time",
                 pch=c(1,19), col = c("#00AFBB", "#E7B800"))
interaction.plot(x.factor = df$n, trace.factor = df$p, 
                 response = df$time, fun = mean, 
                 type = "b", legend = TRUE, 
                 xlab = "n_vert", ylab="time",
                 pch=c(1,19), col = c("#00AFBB", "#E7B800"))
```

```{r Plots}
ggplot(df, aes(x = time, color = n, fill = n)) + geom_density(alpha = 0.1)
ggboxplot(df, x = "n", y = "time", fill = "n", add = "jitter")
ggboxplot(df, x = "p", y = "time", fill = "p", add = "jitter")
ggboxplot(df, x = "n", y = "time", color = "p", add = "jitter")
ggboxplot(df, x = "p", y = "time", color = "n", add = "jitter")
```

## ANOVA ---------------

```{r ANOVA}
res.aov1 <- aov(time ~ p * n, data = df)
summary(res.aov1)
```

## Normalidade plots ---------------

```{r Normalidade dos plots}
plot(res.aov1, 1)
residuals_dinic <- res.aov1$residuals
qqnorm(residuals_dinic)
qqline(residuals_dinic)

hist(residuals_dinic, main="Histogram of residuals", xlab="Residuals")

leveneTest(time ~ n * p, data=df)
```
## Post HOC Analysis ---------------

```{r Post HOC}
TukeyHSD(res.aov1)
plot(TukeyHSD(res.aov1, conf.level=.95), las = 2)
```

## OPT N Paramétrica --------------- Randomization test

```{r}
df$timerand <- df$time
res.aov1 <- aov(timerand ~ p * n, data = df)
FS =summary(res.aov1)[[1]]$F[1]
FP=summary(res.aov1)[[1]]$F[2]
FSP = summary(res.aov1)[[1]]$F[3]
tFS = c(FS)
tFP= c(FP)
tFSP = c(FSP)
for (i in 1:5000){ 
  df$timerand =sample(df$timerand)
res.aov1 <- aov(timerand ~ p * n, data = df)
  pFS =summary(res.aov1)[[1]]$F[1]
  pFP = summary(res.aov1)[[1]]$F[2]
  pFSP = summary(res.aov1)[[1]]$F[3]
  tFS = c(tFS,pFS)
  tFP = c(tFP,pFP)
  tFSP = c(tFSP,pFSP)
}
print(length(tFS[tFS >=FS])/5000)
print(length(tFP[tFP >=FP])/5000)
print(length(tFSP[tFSP >=FSP])/5000)
ggline(df, x = "p", y = "timerand", color = "n", add = c("mean_se"))
ggline(df, x = "n", y = "timerand", color = "p", add = c("mean_se"))
```
